# -*- coding: utf-8 -*-
"""TitanicSurvivalPrediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aWFQfZ2CLNUIPZv5SrgS0GeQIIVbFER_
"""

import pandas as pd

titanic = pd.read_csv("train.csv")

titanic.head()

titanic.isna().sum()

titanic['Age'].mean()

titanic['Age'].fillna(titanic['Age'].mean(), inplace= True)

titanic.dropna(subset=['Embarked'], inplace = True)

titanic.isna().sum()

titanic.head()

titanic.Sex = titanic.Sex.map({'male':0, 'female':1})

titanic = pd.get_dummies(data= titanic, columns=['Embarked'], dtype= int)

titanic.head()

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

from sklearn.model_selection import train_test_split

X = titanic[['Pclass','Sex', 'Age','SibSp','Parch', 'Fare', 'Embarked_C' , 'Embarked_Q', 'Embarked_S']]
y = titanic['Survived']

X.info()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

model.fit(X_train, y_train)

predictions = model.predict(X_test)

predictions

from sklearn.metrics import confusion_matrix, classification_report

print(classification_report(y_test, predictions))

print(confusion_matrix(y_test, predictions))

person = {
    'Pclass': 1,
    'Sex': 1,
    'Age': 25,
    'SibSp': 2,
    'Parch': 0,
    'Fare': 500,
    'Embarked_C':1,
    'Embarked_Q':0,
    'Embarked_S':0
}

person_titanic = pd.DataFrame([person])
person_titanic

model.predict(person_titanic)